# bit operations (need for timsort)

In [ ]:
# вывод числа в двоичном виде
for i in range(10):
    print(bin(i))

0b0
0b1
0b10
0b11
0b100
0b101
0b110
0b111
0b1000
0b1001

In [ ]:
# происходят поразрядные операции над числами в двоичном формате
# если разрядов разное количество, то меньший дополняется нулями слева
# применяются известные and, or, xor
print(8 & 9, bin(8 & 9))
print(8 | 9, bin(8 | 9))
print(8 ^ 9, bin(8 ^ 9))

8 0b1000
9 0b1001
1 0b1

In [ ]:
# унарный оператор, переворачивает биты и как-то дополняет нулями и единицами
# целые числа имеют бит, отвечающий за знак, который тоже инвертируется
# в общем ~N = -(N+1)
for i in range(10):
    print(i, bin(i), ~i, bin(~i))

0 0b0 -1 -0b1
1 0b1 -2 -0b10
2 0b10 -3 -0b11
3 0b11 -4 -0b100
4 0b100 -5 -0b101
5 0b101 -6 -0b110
6 0b110 -7 -0b111
7 0b111 -8 -0b1000
8 0b1000 -9 -0b1001
9 0b1001 -10 -0b1010

In [ ]:
# сдвиги (увеличение и уменьшение в 2 раза)
for i in range(10):
    print(f'{1 << i}\t {bin(1 << i)}')
print()
for i in range(10):
    print(f'{512 >> i}\t {bin(512 >> i)}')

1	 0b1
2	 0b10
4	 0b100
8	 0b1000
16	 0b10000
32	 0b100000
64	 0b1000000
128	 0b10000000
256	 0b100000000
512	 0b1000000000

512	 0b1000000000
256	 0b100000000
128	 0b10000000
64	 0b1000000
32	 0b100000
16	 0b10000
8	 0b1000
4	 0b100
2	 0b10
1	 0b1

In [ ]:
# всё это можно комбинировать
a = 5
print(a, bin(a))
a <<= 1
print(a, bin(a))
a >>= 1
print(a, bin(a))
a |= 5
print(a, bin(a))
a &= 5
print(a, bin(a))
a |= 5 & 1
print(a, bin(a), bin(1))

5 0b101
10 0b1010
5 0b101
5 0b101
5 0b101
5 0b101 0b1

In [ ]:
a = 1000000
while a >= 32:
    a >>= 1
    print(a)

500000
250000
125000
62500
31250
15625
7812
3906
1953
976
488
244
122
61
30

In [ ]:
# 32 == 2**5  -> берём старшие 5 бит
# т е, любое число меньше 32 укладывается в 5 бит

MIN_MERGE = 32

def calc_minrun(n): # n - total number of elements in array
    r = 0
    while n >= MIN_MERGE:
        r |= n & 1  # будет равен 1, если в младших битах есть 1 (после какого-то деления на 2 число будет нечётным)
        n >>= 1 # n ~ уменьшается вдвое
    return n + r

In [ ]:
a = 1000
r = 0
while a >= 32:
    print(f'a = {a}, {bin(a)}')
    r |= a & 1
    print(f'r = {r}, {bin(r)}')
    a >>= 1
    print(f'a + r = {a + r}, {bin(a + r)}')
    print()

a = 1000, 0b1111101000
r = 0, 0b0
a + r = 500, 0b111110100

a = 500, 0b111110100
r = 0, 0b0
a + r = 250, 0b11111010

a = 250, 0b11111010
r = 0, 0b0
a + r = 125, 0b1111101

a = 125, 0b1111101
r = 1, 0b1
a + r = 63, 0b111111

a = 62, 0b111110
r = 1, 0b1
a + r = 32, 0b100000

# timsort

In [1]:
import random

In [2]:
# implementation without final merging
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j+1] = arr[j]
            j -= 1
        arr[j+1] = key
    return arr

MIN_MERGE = 32

def calc_minrun(n):
    r = 0
    while n >= MIN_MERGE:
        r |= n & 1
        n >>= 1
    return n + r

def timsort(arr):
    n = len(arr)
    if n < 64:
        return insertion_sort(arr)

    minrun = calc_minrun(n)

    for start in range(0, n, minrun):
        end = min(start + minrun, n)
        arr[start:end] = insertion_sort(arr[start:end])

    # add merging

    return arr

In [3]:
A = list(range(10**3))
random.shuffle(A)
print(A[:5])
print(timsort(A))

[402, 890, 498, 297, 571]
[12, 18, 33, 116, 162, 194, 214, 258, 279, 287, 294, 297, 335, 373, 382, 402, 498, 530, 560, 570, 571, 700, 735, 741, 748, 842, 859, 890, 914, 931, 967, 998, 60, 74, 98, 102, 122, 130, 131, 215, 234, 236, 237, 252, 341, 369, 397, 403, 465, 466, 567, 590, 600, 627, 720, 742, 818, 828, 862, 896, 954, 957, 958, 969, 8, 25, 58, 97, 119, 142, 146, 163, 197, 250, 308, 320, 386, 464, 474, 479, 480, 505, 506, 584, 605, 619, 639, 657, 678, 693, 759, 773, 776, 781, 871, 910, 23, 69, 169, 186, 202, 256, 431, 478, 493, 495, 502, 542, 562, 563, 614, 617, 629, 635, 638, 656, 659, 670, 689, 698, 747, 750, 765, 798, 840, 854, 946, 964, 48, 56, 100, 138, 139, 233, 257, 263, 293, 306, 324, 339, 349, 359, 418, 496, 499, 591, 626, 697, 699, 749, 772, 811, 813, 825, 839, 953, 965, 966, 986, 987, 49, 54, 112, 144, 213, 221, 261, 282, 296, 355, 365, 414, 424, 438, 485, 501, 512, 546, 580, 625, 684, 696, 754, 757, 766, 821, 858, 869, 932, 941, 951, 990, 63, 67, 83, 84, 87, 110, 141, 148, 348, 360, 363, 420, 422, 455, 557, 593, 598, 624, 640, 647, 730, 778, 793, 802, 820, 843, 861, 866, 867, 902, 976, 980, 89, 104, 128, 154, 167, 182, 185, 199, 243, 337, 357, 367, 388, 425, 447, 456, 472, 548, 551, 643, 646, 686, 711, 753, 784, 806, 829, 832, 856, 875, 889, 982, 35, 36, 41, 46, 115, 158, 165, 177, 179, 184, 207, 225, 229, 230, 336, 362, 393, 412, 436, 442, 577, 683, 705, 785, 812, 817, 857, 860, 907, 961, 981, 991, 34, 55, 80, 108, 109, 155, 178, 224, 248, 265, 343, 364, 370, 415, 477, 492, 517, 527, 545, 576, 651, 780, 807, 836, 838, 864, 868, 901, 905, 917, 918, 921, 16, 40, 57, 77, 211, 223, 241, 276, 305, 323, 325, 352, 450, 452, 494, 514, 565, 620, 631, 632, 636, 661, 680, 722, 745, 756, 804, 823, 903, 925, 942, 968, 10, 30, 93, 118, 150, 164, 187, 200, 238, 254, 366, 377, 399, 416, 433, 488, 491, 533, 536, 630, 666, 725, 763, 771, 786, 848, 884, 927, 928, 977, 995, 999, 9, 105, 129, 168, 242, 251, 262, 266, 272, 277, 292, 310, 351, 384, 423, 439, 457, 528, 572, 597, 645, 654, 702, 714, 717, 775, 789, 850, 882, 945, 960, 970, 17, 44, 124, 171, 183, 222, 239, 244, 247, 285, 289, 313, 338, 353, 385, 387, 405, 429, 513, 531, 653, 692, 707, 721, 723, 770, 809, 874, 891, 915, 971, 993, 11, 20, 24, 26, 52, 53, 64, 70, 99, 143, 159, 193, 228, 253, 270, 280, 298, 332, 378, 476, 555, 574, 611, 615, 650, 709, 764, 774, 777, 899, 904, 913, 4, 5, 6, 28, 47, 73, 81, 114, 135, 153, 172, 188, 203, 240, 281, 300, 407, 413, 444, 453, 460, 518, 519, 538, 553, 578, 679, 682, 719, 768, 909, 924, 65, 76, 101, 134, 145, 149, 189, 190, 246, 267, 274, 290, 314, 315, 329, 391, 419, 487, 566, 569, 592, 621, 622, 688, 739, 883, 885, 908, 934, 947, 963, 983, 71, 123, 147, 180, 198, 245, 328, 398, 451, 475, 529, 541, 550, 568, 579, 681, 701, 740, 751, 790, 791, 792, 795, 827, 834, 845, 920, 922, 933, 955, 979, 992, 21, 91, 170, 217, 231, 255, 259, 260, 268, 273, 350, 374, 404, 417, 510, 552, 641, 703, 706, 746, 794, 816, 830, 841, 865, 894, 926, 973, 974, 984, 988, 989, 13, 103, 106, 140, 161, 204, 283, 288, 319, 344, 394, 410, 435, 504, 522, 561, 610, 616, 633, 634, 695, 732, 736, 755, 800, 822, 835, 849, 877, 887, 930, 972, 1, 45, 125, 206, 208, 209, 227, 342, 356, 383, 389, 396, 401, 463, 540, 581, 582, 583, 585, 586, 587, 601, 606, 664, 674, 676, 758, 761, 881, 886, 906, 948, 2, 66, 136, 196, 218, 219, 226, 269, 284, 312, 334, 340, 380, 441, 489, 575, 604, 648, 667, 668, 669, 673, 744, 779, 803, 814, 826, 929, 938, 962, 994, 996, 14, 22, 59, 61, 72, 210, 264, 291, 295, 327, 354, 358, 379, 428, 437, 445, 449, 467, 468, 490, 500, 564, 662, 801, 805, 852, 863, 876, 892, 919, 937, 940, 43, 68, 90, 111, 157, 192, 278, 307, 317, 462, 481, 516, 532, 544, 559, 594, 602, 652, 665, 671, 704, 708, 712, 715, 724, 726, 769, 819, 824, 872, 949, 978, 7, 29, 32, 39, 94, 117, 191, 249, 301, 311, 316, 322, 345, 372, 376, 408, 434, 459, 523, 524, 596, 607, 642, 691, 727, 788, 808, 855, 897, 911, 944, 959, 0, 3, 27, 38, 132, 181, 195, 216, 235, 302, 304, 333, 381, 395, 458, 473, 483, 497, 534, 537, 554, 573, 603, 644, 655, 694, 713, 787, 837, 851, 898, 936, 42, 107, 133, 156, 166, 275, 309, 330, 406, 421, 430, 432, 454, 508, 509, 521, 543, 556, 660, 672, 675, 690, 729, 799, 878, 888, 912, 923, 935, 939, 943, 997, 19, 31, 37, 50, 62, 92, 113, 120, 121, 152, 160, 205, 220, 286, 326, 361, 390, 392, 484, 589, 623, 628, 687, 728, 733, 734, 762, 767, 870, 893, 895, 975, 15, 51, 75, 78, 82, 88, 212, 299, 331, 400, 461, 470, 486, 503, 515, 520, 547, 558, 599, 618, 663, 710, 716, 738, 760, 783, 810, 831, 853, 879, 950, 952, 86, 96, 127, 137, 174, 175, 271, 303, 346, 347, 368, 375, 440, 448, 471, 507, 511, 535, 539, 588, 608, 609, 612, 613, 637, 649, 718, 752, 796, 815, 844, 880, 85, 95, 126, 151, 173, 176, 201, 232, 318, 409, 426, 427, 443, 446, 469, 482, 525, 526, 595, 677, 685, 731, 743, 782, 833, 846, 847, 873, 900, 916, 956, 985, 79, 321, 371, 411, 549, 658, 737, 797]